import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "50mb" }));

  // Initialize Gemini client on the server
  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });

  // POST /api/generate
  app.post("/api/generate", async (req, res) => {
    const { query } = req.body;
    if (!query) {
      return res.status(400).json({ error: "Query is required" });
    }
    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite-image",
        contents: {
          parts: [{ text: `A hyper-detailed cinematic concept visualization of: ${query}. Masterpiece quality, sharp focus, immersive lighting, artistic excellence, high-resolution style.` }],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9",
          },
        },
      });

      let imageUrl = "";
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image was generated by the model.");
      }

      res.json({ url: imageUrl, type: "image" });
    } catch (error: any) {
      console.error("generate error:", error);
      res.status(error.status || 500).json({ error: error.message || "Failed to generate image" });
    }
  });

  // POST /api/analyze
  app.post("/api/analyze", async (req, res) => {
    const { query, mediaUrl, audience, useLite } = req.body;
    if (!query || !mediaUrl || !audience) {
      return res.status(400).json({ error: "query, mediaUrl, and audience are required" });
    }

    try {
      const modelName = useLite ? "gemini-3.1-flash-lite" : "gemini-3.5-flash";

      const audiencePrompts = {
        seed: "Explain for a 5-year old child. Simple, magical, story-like.",
        sprout: "Explain for a curious student. Educational, insightful, clear facts.",
        oak: "Explain for an expert. Technical, deep analysis, complex systems engineering.",
      };

      const schema = {
        type: Type.OBJECT,
        properties: {
          segments: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                label: { type: Type.STRING },
                format: { type: Type.STRING, enum: ["compact", "stats", "detailed", "mini"] },
                description: { type: Type.STRING },
                category: { type: Type.STRING },
                icon: { type: Type.STRING },
                stats: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      label: { type: Type.STRING },
                      value: { type: Type.STRING },
                    },
                    required: ["label", "value"],
                  },
                },
                bounds: {
                  type: Type.OBJECT,
                  properties: {
                    x: { type: Type.NUMBER },
                    y: { type: Type.NUMBER },
                    width: { type: Type.NUMBER },
                    height: { type: Type.NUMBER },
                  },
                  required: ["x", "y", "width", "height"],
                },
              },
              required: ["label", "format", "description", "icon", "bounds"],
            },
          },
        },
        required: ["segments"],
      };

      const base64Data = mediaUrl.split(",")[1];
      const response = await ai.models.generateContent({
        model: modelName,
        contents: {
          parts: [
            { inlineData: { data: base64Data, mimeType: "image/png" } },
            { text: `Analyze this visualization of "${query}" for an ${audience.toUpperCase()} audience. Style: ${audiencePrompts[audience as keyof typeof audiencePrompts]} Identify 5 key features with percentage coords (0-100).` },
          ],
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: schema,
          tools: useLite ? [] : [{ googleSearch: {} }],
        },
      });

      if (!response.text) {
        throw new Error("No analysis text returned");
      }

      const parsed = JSON.parse(response.text);
      res.json(parsed);
    } catch (error: any) {
      console.error("analyze error:", error);
      res.status(error.status || 500).json({ error: error.message || "Failed to analyze image" });
    }
  });

  // Vite/static asset serving
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
